name: cpp-cmake-mingw-prebuilt-release-actions-workflow
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
      - 'c*'
      
jobs:
  build:
    name: Create Release
    runs-on: windows-latest
    env:
      libraryName: ToDo-List-Widget
#       tagName: v3.7.7_build_19
#       msvc2019TargetZip: vst3sdk-${{ github.ref_name }}-msvc2019.zip
    steps:
        - uses: actions/checkout@v3
        
        - uses: actions/checkout@v3
          with:
            repository: chrispbailey/ToDo-List-Widget
            path: ToDo-List-Widget

        - name: Cancel Previous Runs
          uses: styfle/cancel-workflow-action@0.9.0
          with:
            access_token: ${{ secrets.GITHUB_TOKEN }}
            
        - uses: actions/setup-java@v2
          with:
            distribution: 'adopt'
            java-version: '11'
            
        - uses: actions/setup-java@v2
          with:
            distribution: 'adopt'
            java-version: '8'
            
        - name: set PATH, check mingw version, cmake generate, build and install
          shell: bash
          run: cd ToDo-List-Widget && ../windows.sh
            
#         - name: Archive Release
#           uses: thedoctor0/zip-release@master
#           with:
#             type: 'zip'
#             directory: "vst3sdk/cmake-build"
#             filename: "${{ env.msvc2019TargetZip }}"

#         - name: Release prebuilt
#           uses: ncipollo/release-action@v1
#           with:
#             artifacts: "vst3sdk/cmake-build/${{ env.msvc2019TargetZip }}"
#             allowUpdates: true
#             token: ${{ secrets.GITHUB_TOKEN }}
